### ISSUE TITLE
Introduce EditorConfig

### ISSUE THREAD

**Issue by ss0201** [WillingRing/SimpleChatJpk#12]
http://editorconfig.org/
Install editor plugin and add a config file `.editorconfig`:
```
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{js,coffee,htm,html,css,scss}]
indent_style = space
indent_size = 2
```

If a plugin is not available for your editor, please tell me.

**Comment by jpkha** [comment]
I am using WebStorm, so I suppose I got nothing to do even creating the .editorconfig files, don't you ?

**Comment by ss0201** [comment]
i guess you still need to create .editorconfig file, but you don't need to install any plugin.

**Comment by ss0201** [comment]
actually i'm not quite sure how webstorm works, so if you feel you don't need to create .editorconfig file, just close this issue.

**Comment by jpkha** [comment]
I don't really miss the npm-debug.log. WebStorm said that it was edited by the .editorconfig. So I thought that it an important file to put

**Comment by ss0201** [comment]
i think npm-debug.log is just a log file with debug information, so it's ok to omit it from git repo.
